### ISSUE TITLE
Incomplete API calls

### ISSUE THREAD

**Issue by irinelul** [KT-Yeh/mihomo#2]
It seems that the api calls are always being cut off at the end.
For example I'm only able to pull 5 characters max using the regular api call, and for the example provided in the GIT only 3 (Seele, Sivler Wolf, Jing Yuan)

https://api.mihomo.me/sr_info_parsed/800333171?lang=en

Does this api require pagination? I wasn't able to find any documentation at all about this. Can't seem to make it load all the characters I have.

**Comment by KT-Yeh** [comment]
The api only returns the characters displayed in your in-game profile.

**Comment by irinelul** [comment]
Thanks! Unfortunate to hear.
